from pages import *
from login import *
from register import *
from courses import *
from assignments import *
from tests import *
from common import *
from ta import *
from students import *
from errors import *
