# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('begin_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('instructions', models.TextField()),
                ('submission_limit', models.PositiveIntegerField()),
                ('feedback_level', models.PositiveIntegerField()),
                ('late', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CommonErrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_num', models.PositiveIntegerField()),
                ('name', models.TextField()),
                ('crn', models.PositiveIntegerField()),
                ('term', models.TextField()),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.TextField()),
                ('comments', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('grade', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('onid', models.TextField()),
                ('classes', models.ManyToManyField(to='components.Course')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('onid', models.TextField()),
                ('classes', models.ManyToManyField(to='components.Course')),
                ('department', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='components.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('time_limit', models.PositiveIntegerField()),
                ('result', models.TextField()),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.Assignment')),
                ('common_errors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.CommonErrors')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Department'),
        ),
    ]
