# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('onid', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ta',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='onid',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='onid',
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='components.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ta',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='components.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='components.User'),
            preserve_default=False,
        ),
    ]
